services:
  - type: web
    name: qikcat-waitlist
    env: node
    plan: free
    branch: main
    buildCommand: cd server && npm install
    startCommand: cd server && npm run start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: qikcat
      - key: PORT
        value: "4000"
